import json, os
import time

def convert_cookies_json_to_txt(json_path, txt_path):
    with open(json_path, 'r') as json_file:
        cookies = json.load(json_file)

    with open(txt_path, 'w') as txt_file:
        txt_file.write('# Netscape HTTP Cookie File\n')
        txt_file.write('# This file was generated by a script\n\n')
        for cookie in cookies:
            domain = cookie.get('domain', '')
            include_subdomains = 'TRUE' if domain.startswith('.') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            
            # Handle invalid expiration dates
            try:
                expiry = int(cookie.get('expirationDate', '0'))
                if expiry < 0:
                    expiry = 0
            except ValueError:
                expiry = 0
            
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            txt_file.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

# Paths to your files
json_path = 'data/cookies.json'
txt_path = 'data/cookies.txt'

convert_cookies_json_to_txt(json_path, txt_path)

